#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

if [ -f /usr/lib/helper-scripts/pre.bsh ]; then
   source /usr/lib/helper-scripts/pre.bsh
fi

set -e

update-alternatives --remove x-www-browser /usr/lib/open_link_confirmation
update-alternatives --remove gnome-www-browser /usr/lib/open_link_confirmation

#DEBHELPER#
