#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

if [ -f /usr/lib/pre.bsh ]; then
   source /usr/lib/pre.bsh
fi

set -e

update-alternatives --remove x-www-browser /usr/lib/open_link_confirmation
update-alternatives --remove gnome-www-browser /usr/lib/open_link_confirmation

#DEBHELPER#
