#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

if [ -f /usr/libexec/helper-scripts/pre.bsh ]; then
   source /usr/libexec/helper-scripts/pre.bsh
fi

set -e

update-alternatives --remove x-www-browser /usr/libexec/open-link-confirmation/open-link-confirmation
update-alternatives --remove gnome-www-browser /usr/libexec/open-link-confirmation/open-link-confirmation

#DEBHELPER#
