#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

if [ -f /usr/lib/pre.bsh ]; then
   source /usr/lib/pre.bsh
fi

set -e

update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/lib/open_link_confirmation 105
update-alternatives --install /usr/bin/gnome-www-browser gnome-www-browser /usr/lib/open_link_confirmation 105

#DEBHELPER#
